#!/bin/sh

sleep 20m

while true; do
	inotifywait -q -e close_write --format '%w' geneticDataFiles/currentbest |
	git add geneticDataFiles/currentbest 
	git commit -q -m "auto update: new best at $(date +%d/%m/%y-%R)" 
	git push -q
	echo "New best found at $(date +%d/%m/%y-%R)"
done

