#!/bin/sh

while true; do
	sleep 20m

	inotifywait -q -e close_write --format '%w' geneticDataFiles/currentbest |
	git add geneticDataFiles/currentbest geneticDataFiles/fitness.log
	git commit -q -m "auto update: new best at $(date +%d/%m/%y-%R)"
	git push -q
	echo "New best found at $(date +%d/%m/%y-%R)"
done
