#!/bin/bash

trap killgroup SIGINT

killgroup(){
	echo killing...

	git add geneticDataFiles/currentbest geneticDataFiles/fitness.log
	git commit -q -m "auto update: new best at $(date +%d/%m/%y-%R)"
	git push -q

	kill 0
}

git pull
make
# ./irsim -E 21 -p paramFiles/iriNeuronTesting.txt -e &
#./irsim -E 21 -p paramFiles/breaking.txt -e &
./irsim -E 24 -p paramFiles/iriNeuronTesting.txt -e &
./autopush 2&>autopush.log &
wait
