#!/bin/bash

trap killgroup SIGINT

killgroup(){
	echo killing...

	git add geneticDataFiles/currentbest
	git commit -q -m "auto update: new best at $(date +%d/%m/%y-%R)"
	git push -q

	kill 0
}

git pull
./irsim -E 21 -p paramFiles/iriNeuronTemplate.txt -e &
#./irsim -E 24 -p paramFiles/iriNeuronTemplate.txt -e &
./autopush 2&>autopush.log &
wait
